databases:
  - name: Catalog
    databaseName: catalog_kipi
    user: catalog_kipi_user

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/luglifilho/dscatalog
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: Catalog
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50