databases:
  - name: Catalog
    databaseName: catalog_kipi
    user: catalog_kipi_user

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/luglifilho/dscatalog
   envVars:
   - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIxOTY3MTksInVzZXJfbmFtZSI6Im1hcmlhQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjpbIlJPTEVfT1BFUkFUT1IiLCJST0xFX0FETUlOIl0sImp0aSI6IjdkNTg2MzVmLWEzODctNDcwYi04YTllLTI1OWJmMWIzNzkxOCIsImNsaWVudF9pZCI6ImRzY2F0YWxvZyIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.lOJo7w8Hp0zHJQQnmLhMPf53washIeNdyJW9zU8Zaas
     fromDatabase:
       name: Catalog
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50